name: Build
on:
  release:
    types: [created]

permissions:
  contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
        
    - name: Build
      run: ghc mx2fn.hs

    - name: zip linux artifact
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: tar czvf mx2fn.tar.gz ./mx2fn

    - name: zip macos artifact
      if: ${{ matrix.os == 'macos-latest' }}
      run: tar czvf mx2fn.tar.gz ./mx2fn

    - name: zip windows artifact
      if: ${{ matrix.os == 'windows-latest' }}
      run: 7z a mx2fn.windows-amd64.zip mx2fn.exe
      
    - name: upload linux artifact
      if: ${{ matrix.os == 'ubuntu-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ./mx2fn.tar.gz
        asset_name: mx2fn.linux-amd64.tar.gz
        asset_content_type: application/gzip
        
    - name: upload darwin artifact
      if: ${{ matrix.os == 'macos-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ./mx2fn.tar.gz
        asset_name: mx2fn.darwin-amd64.tar.gz
        asset_content_type: application/gzip
        
    - name: upload windows artifact
      if: ${{ matrix.os == 'windows-latest' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ github.event.release.upload_url }} 
        asset_path: ./mx2fn.windows-amd64.zip
        asset_name: mx2fn.windows-amd64.zip
        asset_content_type: application/zip
